name = "Third Floor Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53b7f35f2c6a608c85d4c53bf50fe9cf8be1eb675dc76d281396326bb9886d93"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "global_packs/required_data"
