name = "Third Floor Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94d270ae7f4290cacc7b489a38018a1aefda9c8a1453789c18e682b8ed8159c1"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "global_packs/required_data"
