[[mods]]
name = "Ad Astra"
url = "https://cdn.modrinth.com/data/3ufwT9JF/versions/IfdLtruQ/ad_astra-fabric-1.20.1-1.15.3.jar"

[[mods]]
name = "Adorn"
url = "https://cdn.modrinth.com/data/E6FUtRJh/versions/HXibuobl/Adorn-5.0.0%2B1.20.1-fabric.jar"

[[mods]]
name = "Alternate Current"
url = "https://cdn.modrinth.com/data/r0v8vy1s/versions/zrRsTCOk/alternate-current-mc1.20-1.7.0.jar"

[[mods]]
name = "AppleSkin"
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/CxnVG86Y/appleskin-fabric-mc1.20-2.5.0.jar"

[[mods]]
name = "Architectury API"
url = "https://cdn.modrinth.com/data/lhGA9TYQ/versions/Sbew3kXe/architectury-9.1.12-fabric.jar"

[[mods]]
name = "Automobility"
url = "https://cdn.modrinth.com/data/rqIsPf9F/versions/G97BY8OB/automobility-0.4.2%2B1.20.1-fabric.jar"

[[mods]]
name = "bad packets"
url = "https://cdn.modrinth.com/data/ftdbN0KK/versions/BTK3ZWby/badpackets-fabric-0.4.2.jar"

[[mods]]
name = "BetterF3"
url = "https://cdn.modrinth.com/data/8shC1gFX/versions/FtJ0KSLo/BetterF3-7.0.1-Fabric-1.20.1.jar"

[[mods]]
name = "Bewitchment"
url = "https://cdn.modrinth.com/data/AKbBSvuC/versions/MDlqsrqA/bewitchment-1.20-6.jar"

[[mods]]
name = "Bits And Chisels"
url = "https://cdn.modrinth.com/data/q8MC5tW2/versions/kqHohJYy/bitsandchisels-2.7.3.jar"

[[mods]]
name = "BlueMap"
url = "https://cdn.modrinth.com/data/swbUV1cr/versions/km6iyWPb/BlueMap-3.16-fabric-1.20.jar"

[[mods]]
name = "Bobby"
url = "https://cdn.modrinth.com/data/M08ruV16/versions/lwQhE0t0/bobby-5.0.0.jar"

[[mods]]
name = "Botarium"
url = "https://cdn.modrinth.com/data/2u6LRnMa/versions/YgOh7n9M/botarium-fabric-1.20.1-2.2.0.jar"

[[mods]]
name = "Concurrent Chunk Management Engine (Fabric)"
url = "https://cdn.modrinth.com/data/VSNURh3q/versions/oXqihlMj/c2me-fabric-mc1.20.1-0.2.0%2Balpha.10.100.jar"

[[mods]]
name = "Cardinal Components API"
url = "https://cdn.modrinth.com/data/K01OU20C/versions/qW85eawp/cardinal-components-api-5.2.2.jar"

[[mods]]
name = "CC: Tweaked"
url = "https://cdn.modrinth.com/data/gu7yAYhd/versions/LqBYIKkR/cc-tweaked-1.20.1-fabric-1.108.0.jar"

[[mods]]
name = "Cinderscapes"
url = "https://cdn.modrinth.com/data/QC4wcUXZ/versions/HCDPkEm0/cinderscapes-4.0.8.jar"

[[mods]]
name = "Cloth Config API"
url = "https://cdn.modrinth.com/data/9s6osm5g/versions/s7VTKfLA/cloth-config-11.1.106-fabric.jar"

[[mods]]
name = "Collective"
url = "https://cdn.modrinth.com/data/e0M1UDsY/versions/W1CQ9UCz/collective-1.20.1-6.65.jar"

[[mods]]
name = "Couplings"
url = "https://cdn.modrinth.com/data/80ulerjA/versions/1S2TEbqR/Couplings-1.9.4%2B1.20.jar"

[[mods]]
name = "Create Fabric"
url = "https://cdn.modrinth.com/data/Xbc0uyRg/versions/qlA1WuOK/create-fabric-0.5.1-d-build.1161%2Bmc1.20.1.jar"

[[mods]]
name = "Create: Steam 'n' Rails"
url = "https://cdn.modrinth.com/data/ZzjhlDgM/versions/TQd7SsHW/Steam_Rails-1.5.0%2Bfabric-mc1.20.1-build.15.jar"

[[mods]]
name = "Create Utilities"
url = "https://cdn.modrinth.com/data/PRHeWeBs/versions/DGd6wl7I/createutilities-0.1.3%2B1.20.1.jar"

[[mods]]
name = "Create Crafts & Additions"
url = "https://cdn.modrinth.com/data/kU1G12Nn/versions/ogRcUOQY/createaddition-fabric%2B1.20.1-0.9.0.jar"

[[mods]]
name = "Croptopia"

[[mods]]
name = "ChoiceTheorem's Overhauled Village"
url = "https://cdn.modrinth.com/data/fgmhI8kH/versions/j7JHN8EG/ctov-3.3.4.jar"

[[mods]]
name = "Cull Less Leaves"
url = "https://cdn.modrinth.com/data/iG6ZHsUV/versions/TFvkv8XK/CullLessLeaves-1.3.0.jar"

[[mods]]
name = "Iron Chests"
url = "https://cdn.modrinth.com/data/7mHyGgvW/versions/kpG7ZU4m/IronChests-2.0.0.jar"

[[mods]]
name = "Dawn API"
url = "https://cdn.modrinth.com/data/meZK2DCX/versions/J6b05anw/dawn-5.0.0.jar"

[[mods]]
name = "Debugify"
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/6XDJoCks/Debugify-1.20.1%2B2.0.jar"

[[mods]]
name = "Eating Animation"
url = "https://cdn.modrinth.com/data/rUgZvGzi/versions/OcHlWpeQ/eating-animation-1.9.4%2B1.20.jar"

[[mods]]
name = "Enhanced Block Entities"
url = "https://cdn.modrinth.com/data/OVuFYfre/versions/i3v1Skck/enhancedblockentities-0.9%2B1.20.jar"

[[mods]]
name = "EMI Loot"
url = "https://cdn.modrinth.com/data/qbbO7Jns/versions/7fjkgVEh/emi_loot-0.6.5%2B1.20.1.jar"

[[mods]]
name = "EMI"
url = "https://cdn.modrinth.com/data/fRiHVvU7/versions/K2ePWegL/emi-1.0.19%2B1.20.1%2Bfabric.jar"

[[mods]]
name = "EMIffect"
url = "https://cdn.modrinth.com/data/705gWllI/versions/snwqJj9A/emiffect-fabric-1.1.1%2Bmc1.20.1.jar"

[[mods]]
name = "EMI Trades"
url = "https://cdn.modrinth.com/data/j2HhbEE7/versions/hlcZDRJ1/emitrades-fabric-1.2.0%2Bmc1.20.1.jar"

[[mods]]
name = "Enchanting Infuser"
url = "https://cdn.modrinth.com/data/ePv85y52/versions/2NxkjBtw/EnchantingInfuser-v8.0.1-1.20.1-Fabric.jar"

[[mods]]
name = "Entity Culling"
url = "https://cdn.modrinth.com/data/NNAgCjsB/versions/d20sUcYn/entityculling-fabric-1.6.2-mc1.20.jar"

[[mods]]
name = "Expanded copper"
url = "https://cdn.modrinth.com/data/kJ08cVvv/versions/pDPesYOK/extended-copper-1.4.2-1.20.jar"

[[mods]]
name = "EMI Addon: Extra Mod Integrations"
url = "https://cdn.modrinth.com/data/bpRHnWUb/versions/juXS5CaW/extra-mod-integrations-0.4.1%2B1.20.1.jar"

[[mods]]
name = "Fastload"
url = "https://cdn.modrinth.com/data/kCpssoSb/versions/ys9T20o4/Fastload%2B1.18.2-1.20-3.4.0.jar"

[[mods]]
name = "FerriteCore"
url = "https://cdn.modrinth.com/data/uXXizFIs/versions/FCnCG6PS/ferritecore-6.0.0-fabric.jar"

[[mods]]
name = "Forge Config API Port"
url = "https://cdn.modrinth.com/data/ohNO6lps/versions/CtENDTlF/ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar"

[[mods]]
name = "Geckolib"
url = "https://cdn.modrinth.com/data/8BmcQJ2H/versions/V5QnDeov/geckolib-fabric-1.20.1-4.2.2.jar"

[[mods]]
name = "Global Packs"
url = "https://cdn.modrinth.com/data/NRLPy2mk/versions/WjtRRTw9/global_packs-quilt-1.19.4-1.16.1_quilt.jar"

[[mods]]
name = "Immersive Structures II: Nether edition"
url = "https://cdn.modrinth.com/data/fECIioDQ/versions/tMnaV87R/imst_n-1.1.0.jar"

[[mods]]
name = "Immersive structures"
url = "https://cdn.modrinth.com/data/CVBAErky/versions/C1fCIQSh/imst-2.1.0.jar"

[[mods]]
name = "Indium"
url = "https://cdn.modrinth.com/data/Orvt0mRa/versions/yTh7W27h/indium-1.0.21%2Bmc1.20.1.jar"

[[mods]]
name = "Iris"
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/URWeWMAt/iris-mc1.20-1.6.4.jar"

[[mods]]
name = "JamLib"
url = "https://cdn.modrinth.com/data/IYY9Siz8/versions/vVYtBiuW/jamlib-0.6.1%2B1.20.x.jar"

[[mods]]
name = "Krypton"
url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/jiDwS0W1/krypton-0.2.3.jar"

[[mods]]
name = "LambdaBetterGrass"
url = "https://cdn.modrinth.com/data/2Uev7LdA/versions/Fhyj2P7Q/lambdabettergrass-1.5.2%2B1.20.1.jar"

[[mods]]
name = "LazyDFU"
url = "https://cdn.modrinth.com/data/hvFnDODi/versions/0.1.3/lazydfu-0.1.3.jar"

[[mods]]
name = "Lithium"
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/ZSNsJrPI/lithium-fabric-mc1.20.1-0.11.2.jar"

[[mods]]
name = "Memory Leak Fix"
url = "https://cdn.modrinth.com/data/NRjRiSSD/versions/dGlflhb6/memoryleakfix-fabric-1.17%2B-1.1.2.jar"

[[mods]]
name = "Mine Cells - Dead Cells Mod"
url = "https://cdn.modrinth.com/data/9Qdvz1OV/versions/hgpfupbt/minecells-1.5.5.jar"

[[mods]]
name = "MixinTrace"
url = "https://cdn.modrinth.com/data/sGmHWmeL/versions/1.1.1%2B1.17/mixintrace-1.1.1%2B1.17.jar"

[[mods]]
name = "Model Gap Fix"
url = "https://cdn.modrinth.com/data/QdG47OkI/versions/r6uVoUxU/modelfix-1.14-fabric.jar"

[[mods]]
name = "Modern Industrialization"
url = "https://cdn.modrinth.com/data/Gov5Dboq/versions/4aMaIuZb/Modern-Industrialization-1.7.3.jar"

[[mods]]
name = "Mod Menu"
url = "https://cdn.modrinth.com/data/mOgUt4GM/versions/eTCL1uh8/modmenu-7.2.1.jar"

[[mods]]
name = "More Mob Variants"
url = "https://cdn.modrinth.com/data/JiEhJ3WG/versions/j403kQd0/moremobvariants-fabric%2B1.20-1.2.2.jar"

[[mods]]
name = "No Chat Reports"
url = "https://cdn.modrinth.com/data/qQyHxfxd/versions/HeZZR2kF/NoChatReports-FABRIC-1.20.1-v2.2.2.jar"

[[mods]]
name = "OttahMod"
url = "https://cdn.modrinth.com/data/891G4kho/versions/33ZlHe9v/ottah-A2-pre_1.jar"

[[mods]]
name = "oÏ‰o (owo-lib)"
url = "https://cdn.modrinth.com/data/ccKDOlHs/versions/m23n3uIM/owo-lib-0.11.1%2B1.20.jar"

[[mods]]
name = "Patchouli"
url = "https://cdn.modrinth.com/data/nU0bVIaL/versions/tzz6fEoj/Patchouli-1.20.1-81-FABRIC.jar"

[[mods]]
name = "Pehkui"
url = "https://cdn.modrinth.com/data/t5W7Jfwy/versions/ooQsxSVg/Pehkui-3.7.8%2B1.14.4-1.20.1.jar"

[[mods]]
name = "Plushie-Mod"
url = "https://cdn.modrinth.com/data/hsOK0gUP/versions/jvg1RnBf/plushies-1.3.0-fabric.jar"

[[mods]]
name = "Presence Footsteps"
url = "https://cdn.modrinth.com/data/rcTfTZr3/versions/FMF3yzCR/PresenceFootsteps-1.9.0.jar"

[[mods]]
name = "Profundis: Seven New Quality Cave Biomes"
url = "https://cdn.modrinth.com/data/aucz7XCt/versions/PyaRCgYQ/profundis-1.6.0.jar"

[[mods]]
name = "Promenade"
url = "https://cdn.modrinth.com/data/GuE5FpvB/versions/F17sFUaS/promenade-4.1.0.jar"

[[mods]]
name = "Puzzles Lib"
url = "https://cdn.modrinth.com/data/QAGBst4M/versions/KGAO1rK6/PuzzlesLib-v8.0.24-1.20.1-Fabric.jar"

[[mods]]
name = "Quilt Kotlin Libraries (QKL)"
url = "https://cdn.modrinth.com/data/lwVhp9o5/versions/9WIAwhe7/quilt-kotlin-libraries-2.1.2%2Bkt.1.9.0%2Bflk.1.10.8.jar"

[[mods]]
name = "Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL)"
url = "https://cdn.modrinth.com/data/qvIfYCYJ/versions/DzBePwtf/qfapi-7.2.1_qsl-6.1.1_fapi-0.88.0_mc-1.20.1.jar"

[[mods]]
name = "Qu Enchantments"
url = "https://cdn.modrinth.com/data/5RGE5YW5/versions/pXmkO2BV/qu-enchantments-1.3.6-1.20.jar"

[[mods]]
name = "ramel"
url = "https://cdn.modrinth.com/data/4Uw92C2y/versions/3Zq4GcTg/ramel-0.1.0%2Bmc1.20.1.jar"

[[mods]]
name = "Resourceful Config"
url = "https://cdn.modrinth.com/data/M1953qlQ/versions/nVDWZ9N7/resourcefulconfig-fabric-1.20.1-2.1.0.jar"

[[mods]]
name = "Resourceful Lib"
url = "https://cdn.modrinth.com/data/G1hIVOrD/versions/Km7wGxHM/resourcefullib-fabric-1.20.1-2.1.10.jar"

[[mods]]
name = "Scorched"
url = "https://cdn.modrinth.com/data/yID404Mu/versions/dy1TW0Rk/scorched-1.1.3c.jar"

[[mods]]
name = "Server Tick"
url = "https://cdn.modrinth.com/data/nEKRNLz9/versions/IOYJbkmQ/servertick-mc1.20-1.8.jar"

[[mods]]
name = "Simple Voice Chat"
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/Nc9kJWyt/voicechat-quilt-1.20.1-2.4.24.jar"

[[mods]]
name = "Snow Under Trees (Fabric)"
url = "https://cdn.modrinth.com/data/XVnUIUAQ/versions/c2a6rdtw/snow-under-trees-fabric-1.1.0%2B1.20.jar"

[[mods]]
name = "Sodium"
url = "https://cdn.modrinth.com/data/AANobbMI/versions/vgceLbdH/sodium-fabric-mc1.20-0.4.10%2Bbuild.27.jar"

[[mods]]
name = "spark"
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/XGW2fviP/spark-1.10.53-fabric.jar"

[[mods]]
name = "Starlight (Fabric)"
url = "https://cdn.modrinth.com/data/H8CaAYZC/versions/XGIsoVGT/starlight-1.1.2%2Bfabric.dbc156f.jar"

[[mods]]
name = "Terralith"
url = "https://cdn.modrinth.com/data/8oi3bsk5/versions/hYoo0DKV/Terralith_1.20.1_v2.4.5.jar"

[[mods]]
name = "Things"
url = "https://cdn.modrinth.com/data/VzAGdu9D/versions/4osKFK3P/things-0.3.1%2B1.20.jar"

[[mods]]
name = "Tom's Simple Storage Mod"
url = "https://cdn.modrinth.com/data/XZNI4Cpy/versions/gT2rdlHL/toms_storage_fabric-1.20-1.6.4.jar"

[[mods]]
name = "Tree Harvester"
url = "https://cdn.modrinth.com/data/abooMhox/versions/c2klaSgQ/treeharvester-1.20.1-8.2.jar"

[[mods]]
name = "Trinkets"
url = "https://cdn.modrinth.com/data/5aaWibi9/versions/e563ycts/trinkets-3.7.1.jar"

[[mods]]
name = "Twigs"
url = "https://cdn.modrinth.com/data/RG50cUrX/versions/aJj6NXkv/twigs-3.1.0-fabric.jar"

[[mods]]
name = "Universal Graves"
url = "https://cdn.modrinth.com/data/yn9u3ypm/versions/RqVbvts1/graves-3.0.0-pre.1%2B1.20.1.jar"

[[mods]]
name = "Useless Reptile"
url = "https://cdn.modrinth.com/data/YE4QRt8F/versions/renOQLwR/uselessreptile-0.5.0-1.20.1.jar"

[[mods]]
name = "Victus - Custom Hearts"
url = "https://cdn.modrinth.com/data/Sy5mAKPK/versions/HzFLIayb/victus-0.1.14%2B1.20.jar"

[[mods]]
name = "VillagersPlus"
url = "https://cdn.modrinth.com/data/oHGMwNDR/versions/QtzrqUgt/VillagersPlus_2.1_%28FABRIC%29_for_1.20.1.jar"

[[mods]]
name = "Very Many Players (Fabric)"
url = "https://cdn.modrinth.com/data/wnEe9KBa/versions/J2WKvX2m/vmp-fabric-mc1.20.1-0.2.0%2Bbeta.7.101-all.jar"

[[mods]]
name = "Wilder Wild"
url = "https://cdn.modrinth.com/data/AtHRJSUW/versions/1B31drs9/WilderWild-2.1.1-Fabric%2B1.20.1.jar"

[[mods]]
name = "Windchimes"
url = "https://cdn.modrinth.com/data/iM50gcBD/versions/JapPN4QV/windchimes-1.2.4%2B1.20.jar"

[[mods]]
name = "WTHIT"
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/SbNRrrGr/wthit-quilt-8.4.0.jar"

[[mods]]
name = "Xaero's Minimap (Fair-Play)"
url = "https://cdn.modrinth.com/data/JkSi2Fzx/versions/6aPaqLkt/Xaeros_Minimap_FP23.6.3_Fabric_1.20.jar"

[[mods]]
name = "Xaero's World Map"
url = "https://cdn.modrinth.com/data/NcUtCpym/versions/qwwKbodF/XaerosWorldMap_1.34.0_Fabric_1.20.jar"

[[mods]]
name = "Yet Another Cobblestone Generator"
url = "https://cdn.modrinth.com/data/xPsKRMUF/versions/gX5yMtYZ/yacg-2023.7.3.jar"

[[mods]]
name = "YetAnotherConfigLib"
url = "https://cdn.modrinth.com/data/1eAoo2KR/versions/VPm1SrE4/yet-another-config-lib-fabric-3.1.1%2B1.20.jar"

[[mods]]
name = "Zoomify"
url = "https://cdn.modrinth.com/data/w7ThoJFB/versions/gZr7EykF/Zoomify-2.11.2.jar"

