name = "Third Floor Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98e98fb5d6380cd88e9c41d9b90b7aa01578b834a8030d41e92864da74e206a7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "global_packs/required_data"
