name = "Third Floor Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bee2059ae6a1766d13fc56847382e5e0bd3a07353b5c10dfa3e4fd240e12bef6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
