name = "Third Floor Modpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "399f83c8887e79ecca00ceb7a7185aaee481d0266380ed11d5edd78c40c6655e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "global_packs/required_data"
